# Makefile for programming the ATtiny85
# modified the one generated by CrossPack

DEVICE      = attiny85
CLOCK      = 8000000
PROGRAMMER = -c usbtiny 
OBJECTS    = ps2midi.o uart_send.o
# for ATTiny85
# see http://www.engbedded.com/fusecalc/
FUSES       = -U lfuse:w:0x62:m -U hfuse:w:0xdf:m -U efuse:w:0xff:m 

# Tune the lines below only if you know what you are doing:
AVRDUDE = avrdude $(PROGRAMMER) -p $(DEVICE)
COMPILE = avr-gcc -Wall -Os -DF_CPU=$(CLOCK) -mmcu=$(DEVICE)

# symbolic targets:
all:	ps2midi.hex

.c.o:
	$(COMPILE) -c $< -o $@

.S.o:
	$(COMPILE) -x assembler-with-cpp -c $< -o $@

.c.s:
	$(COMPILE) -S $< -o $@

flash:	all
	$(AVRDUDE) -U flash:w:ps2midi.hex:i

fuse:
	$(AVRDUDE) $(FUSES)

# Xcode uses the Makefile targets "", "clean" and "install"
install: flash fuse

# if you use a bootloader, change the command below appropriately:
load: all
	bootloadHID ps2midi.hex

clean:
	rm -f ps2midi.hex ps2midi.elf $(OBJECTS)

# file targets:
ps2midi.elf: $(OBJECTS)
	$(COMPILE) -o ps2midi.elf $(OBJECTS)

ps2midi.hex: ps2midi.elf
	rm -f ps2midi.hex
	avr-objcopy -j .text -j .data -O ihex ps2midi.elf ps2midi.hex
#	avr-size --format=avr --mcu=$(DEVICE) ps2midi.elf
	avr-size ps2midi.elf
# If you have an EEPROM section, you must also create a hex file for the
# EEPROM and add it to the "flash" target.

# Targets for code debugging and analysis:
disasm:	ps2midi.elf
	avr-objdump -d ps2midi.elf

cpp:
	$(COMPILE) -E serkey.c
